[build]
  command = "npm run build:functions"
  functions = "netlify/functions"
  publish = "frontend/build"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "frontend/build"
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
